-- PDF Report Designer: repository tables. Idempotent: an existing table is kept.
set define off

declare
  procedure run(p_sql varchar2) is
  begin
    execute immediate p_sql;
  exception
    when others then
      -- already exists / already has the column or constraint
      if sqlcode not in (-955, -1430, -2260, -2261, -2275, -1408, -2443, -1442) then
        raise;
      end if;
  end;
begin
  -- one row per report: its code (used by the API), its page setup and layout (JSON)
  run(q'[create table pdf_reports (
    report_id    number generated by default on null as identity primary key,
    code         varchar2(60)   not null,
    name         varchar2(200)  not null,
    description  varchar2(4000),
    layout       clob,
    created_by   varchar2(255)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on   date           default on null sysdate not null,
    updated_by   varchar2(255),
    updated_on   date,
    constraint pdf_reports_code_uk unique (code),
    constraint pdf_reports_code_ck check (code = upper(code) and regexp_like(code, '^[A-Z][A-Z0-9_]*$')),
    constraint pdf_reports_layout_ck check (layout is json))]');

  -- the queries of a report: Q1 .. Q10
  run(q'[create table pdf_queries (
    report_id    number        not null references pdf_reports on delete cascade,
    alias        varchar2(10)  not null,
    seq          number        not null,
    title        varchar2(200),
    sql_text     clob          not null,
    constraint pdf_queries_pk primary key (report_id, alias),
    constraint pdf_queries_alias_ck check (regexp_like(alias, '^Q([1-9]|10)$')))]');

  -- images (logos, stamps, signatures) used by the layouts, stored as JPEG
  run(q'[create table pdf_images (
    image_id     number generated by default on null as identity primary key,
    name         varchar2(200)  not null,
    mime_type    varchar2(100)  default on null 'image/jpeg' not null,
    width        number,
    height       number,
    content      blob           not null,
    created_by   varchar2(255)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_on   date           default on null sysdate not null,
    constraint pdf_images_name_uk unique (name))]');

  -- one row per generated PDF (who, which report, how long, how big) - kept for 90 days by the API
  run(q'[create table pdf_log (
    log_id       number generated by default on null as identity primary key,
    report_code  varchar2(60),
    app_id       number,
    page_id      number,
    app_user     varchar2(255),
    params       varchar2(4000),
    pages        number,
    bytes        number,
    elapsed_ms   number,
    error        varchar2(4000),
    created_on   date default on null sysdate not null)]');
  run('create index pdf_log_created_ix on pdf_log (created_on)');
end;
/
